### ISSUE TITLE
Replimat building FX showing across maps

### ISSUE THREAD

**Issue by DDimerth** [sumghai/Replimat#21]
![20190508152602_1](https://user-images.githubusercontent.com/50396123/57354467-7dc3bb00-71a6-11e9-9f06-3afca8540d9b.jpg)
![20190508152609_1](https://user-images.githubusercontent.com/50396123/57354484-89af7d00-71a6-11e9-857e-be8bbfa57d91.jpg)
as you can see, my replimat hopper was glowing on the first settlement(2'rd picture, ).
then, i saw this glowing animation on my secondary settlement(1'st picture/ the glowing animation wasn't viable while paused)
i think this lighting is generated on the same coordinate of the replimat hopper which was on the first settlement.
as it is a simple visual problem, i'm just noticing you here.
thx for good mod.

**Comment by sumghai** [comment]
Yup, this is a confirmed bug - it looks like I forgot to specify the map parameter for the FX draw calls.

Thanks for your report!

**Comment by sumghai** [comment]
Fixed as part of e30eb62b09b723d4872af857df2d3ba8c0c3ef60 and 130f80c63bb73f54d97c2f3bdc4d288f63f66559.
