### ISSUE TITLE
Non-human pawns from Humanoid Alien Races 2.0 cannot use Replimats

### ISSUE THREAD

**Issue by sumghai** [sumghai/Replimat#22]
A number of Steam users have reported that non-human pawns from @erdelf's Humanoid Alien Races 2.0 framework end up starving because they can neither use Replimat Terminals nor eat meals already prepared elsewhere.

**Background**
- Most users reporting this issue were using Android Tiers, which is based on the HAR 2.0 framework
- I tested a stripped-down savegame with Replimat, the HAR 2.0 framework and various non-human colonist mods (Orassans, Leeani, Android Tiers etc.), all of whom experienced the same problem

**Analysis**
- It is likely that the current logic for determining who can use Replimat Terminals are somehow excluding non-humans
- @erdelf (via Discord) says that (to his knowledge) his mod only affects/patches `ThoughtsFromIngesting` and `CanEverEat`, and so it theoretically should not be conflicting with our mod

**Comment by erdelf** [comment]
Just to be clear, these are the only two patches I can see being related to eating. If you find anything please pet me know.

**Comment by sumghai** [comment]
Cheers @erdelf, I've just amended my initial report.

**Comment by sumghai** [comment]
@Dubwise56 performed some tests with HAR 2.0 and Replimat, and believes that it is simply a load order issue - he managed to get non-human pawns from the Drow and Arachne mods to eat from Replimat Terminals.

The recommended mod order is:
- Replimat
- HAR 2.0
- Any third-party race mod powered by HAR

I will test Dub's recommendations tonight with Drow, Arachne, Orassans and Android Tiers mods.

**Comment by sumghai** [comment]
Okay, I've successfully confirmed that HAR 2.0 works fine with Replimat, as long as Replimat is positioned earlier in the mod load order. I have Drows, Arachne, Orassans and Androids all eating from Terminals as normal.

I'll announce this workaround to Steam users first, and wait a while before closing this issue.

**Comment by sumghai** [comment]
Further testing from @Dubwise56 suggests load order is actually irrelevant.

I also found that adding HAR 2.0 to some existing savegames with Replimat works fine, while others don't. Which is strange, because they have virtually identical mod lists.

Perhaps the best piece of advice would be to simply start a new save if using with HAR 2.0.

**Comment by sumghai** [comment]
I haven't heard back from any of the users who originally reported the problem, even after I posted the workaround on Steam. I can only assume that they have resolved the issues and simply failed to report back.

Closing.
