### ISSUE TITLE
Prison Labor conflicts with Replimat

### ISSUE THREAD

**Issue by AppleConnoiseur** [sumghai/Replimat#24]
When a prisoner is downed you can't capture them either through a **WorkGiver** or through the right-click **FloatMenu**. I do not know which end the bug lies with, but it fixes itself when I uninstall the Replimat Terminal.

> Diver threw exception in WorkGiver DeliverFoodToPrisoner: System.NullReferenceException: Object reference not set to an instance of an object
> at PrisonLabor.FoodUtility_Tweak.ThoughtsFromIngesting (Verse.Pawn,Verse.Thing) <0x00101>
> at PrisonLabor.FoodUtility_Tweak.FoodSourceOptimality (Verse.Pawn,Verse.Thing,single,bool) <0x00297>
> at PrisonLabor.FoodUtility_Tweak.SpawnedFoodSearchInnerScan (Verse.Pawn,Verse.IntVec3,System.Collections.Generic.List`1<Verse.Thing>,Verse.AI.PathEndMode,Verse.TraverseParms,single,System.Predicate`1<Verse.Thing>) <0x001c7>
> at PrisonLabor.FoodUtility_Tweak.BestFoodSourceOnMap (Verse.Pawn,Verse.Pawn,bool,RimWorld.FoodPreferability,bool,bool,bool,bool,bool,bool,bool) <0x00665>
> at PrisonLabor.FoodUtility_Tweak.TryFindBestFoodSourceFor (Verse.Pawn,Verse.Pawn,bool,Verse.Thing&,Verse.ThingDef&,bool,bool,bool,bool,bool) <0x002db>
> at PrisonLabor.WorkGiver_Warden_DeliverFood_Tweak.JobOnThing (Verse.Pawn,Verse.Thing,bool) <0x00206>
> at RimWorld.WorkGiver_Scanner.HasJobOnThing (Verse.Pawn,Verse.Thing,bool) <0x00031>
> at PrisonLabor.HarmonyPatches.Patch_LaborForbid/<>c__DisplayClass1_0.<CreatePredicate>b__0 (Verse.Thing) <0x00056>
> at Verse.GenClosest/<ClosestThingReachable>c__AnonStorey0.<>m__0 (Verse.Thing) <0x000fa>
> at Verse.GenClosest.ClosestThing_Global (Verse.IntVec3,System.Collections.IEnumerable,single,System.Predicate`1<Verse.Thing>,System.Func`2<Verse.Thing, single>) <0x00214>
> at Verse.GenClosest.ClosestThingReachable (Verse.IntVec3,Verse.Map,Verse.ThingRequest,Verse.AI.PathEndMode,Verse.TraverseParms,single,System.Predicate`1<Verse.Thing>,System.Collections.Generic.IEnumerable`1<Verse.Thing>,int,int,bool,Verse.RegionType,bool) <0x00506>
> at (wrapper dynamic-method) RimWorld.JobGiver_Work.TryIssueJobPackage_Patch1 (object,Verse.Pawn,Verse.AI.JobIssueParams) <0x0135a>
> 
> Verse.Log:Error(String, Boolean)
> RimWorld.JobGiver_Work:TryIssueJobPackage_Patch1(Object, Pawn, JobIssueParams)
> Verse.AI.ThinkNode_PrioritySorter:TryIssueJobPackage(Pawn, JobIssueParams)
> Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn, JobIssueParams)
> Verse.AI.ThinkNode_Tagger:TryIssueJobPackage(Pawn, JobIssueParams)
> Verse.AI.ThinkNode_Subtree:TryIssueJobPackage(Pawn, JobIssueParams)
> Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn, JobIssueParams)
> Verse.AI.ThinkNode_Conditional:TryIssueJobPackage(Pawn, JobIssueParams)
> Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn, JobIssueParams)
> Verse.AI.Pawn_JobTracker:DetermineNextJob(ThinkTreeDef&)
> Verse.AI.Pawn_JobTracker:TryFindAndStartJob()
> Verse.AI.Pawn_JobTracker:EndCurrentJob_Patch1(Object, JobCondition, Boolean)
> Verse.AI.JobDriver:EndJobWith(JobCondition)
> Verse.AI.JobDriver:CheckCurrentToilEndOrFail()
> Verse.AI.JobDriver:DriverTick_Patch1(Object)
> Verse.AI.Pawn_JobTracker:JobTrackerTick()
> Verse.Pawn:Tick_Patch2(Object)
> Verse.TickList:Tick()
> Verse.TickManager:DoSingleTick()
> Verse.TickManager:TickManagerUpdate()
> Verse.Game:UpdatePlay()
> Verse.Root_Play:Update()

**Comment by sumghai** [comment]
I've confirmed this bug with at least one other Steam user.

I consulted with @Dubwise56 via Discord, and the issue lies in the fact that Prison Labor uses its own  food utils / meal logic separate from the vanilla system.

Replimat, on the hand, treats its Terminals like the vanilla Paste Dispenser, and simply modifies the vanilla meal logic system to ensure compatibility with most other mods.

I'll have to contact Avius to see if he can modify Prison Labor's food utils to use the vanilla system instead.

**Comment by sumghai** [comment]
Avius admits that the problem is on his end - he originally had a proper fix in the dev branch of Prison Labor, but it has gotten so out of sync with the master branch that he ended up simply duplicating several vanilla food utils as a stopgap measure.

Since he's not sure if and when he'll ever get around to fixing it for a future release, the ball's in his court now.

**Comment by sumghai** [comment]
Unfortunately, it seems that Avius doesn't really plan on permanently fixing Prison Labor to not detour/duplicate vanilla food utils.

After further consultation with @Dubwise56, we agreed that it is not feasible for us to try and patch around other third-party mods that deviate from vanilla behaviour. So for the time being, this is out of our hands.
