### ISSUE TITLE
Plant scraps as raw resource, or a list of resources allowed in a Def

### ISSUE THREAD

**Issue by SymbolicFrank** [sumghai/Replimat#26]
Plant scraps from Rainbeau's Fertile Fields mod seem like the exact thing you would put in the hopper if you had a replicator IRL. Could they be added?

Alternatively, if you put the allowed raw resources in a Def (XML file), users could add the ones they liked themselves.

**Comment by sumghai** [comment]
> Plant scraps from Rainbeau's Fertile Fields mod seem like the exact thing you would put in the hopper if you had a replicator IRL. Could they be added?

I definitely agree that any organic material like Plant scraps should be allowed inside the Replimat Hoppers, and I think I can easily cobble together a patch for this.

> Alternatively, if you put the allowed raw resources in a Def (XML file), users could add the ones they liked themselves.

I'm not keen on requiring players to edit def files, as a lot of things can go wrong if the user is inexperienced. I would either simply add patches in response to compatibility requests (just like what I'm doing for my CE: FastTrack side project), or expose the appropriate settings in the Mod Options menu.

Also, say that a player manually edits a def file to allow a third-party item, then later accidentally disables the mod that said item comes from. The mod and the game would throw nasty errors as it now can't find the item (whereas patches check to see if a specified mod is running before attempting to look for the item, and will fail gracefully if the mod is absent).

**Comment by sumghai** [comment]
@SymbolicFrank, can you please test the following development build version of Replimat?:

https://github.com/sumghai/Replimat/archive/f384638a467f5854deb52053e43980b8608d8d20.zip

**Comment by SymbolicFrank** [comment]
Thanks, that does work. Which is interesting, because I figured that's what I needed to change and I made that exact same change a few days ago to Buildings_Replimat.xml, but that didn't work. So you need patches for that. Or I made a mistake.

**Comment by sumghai** [comment]
Okay, I'll wrap this up for the next update. No ETA yet.
