### ISSUE TITLE
Animals not using Replimat Animal Feeder

### ISSUE THREAD

**Issue by shiuanyue** [sumghai/Replimat#29]
Animals do not use Replimat Animal Feeder
動物不使用飼料合成器(我能用中文嗎?

**Comment by sumghai** [comment]
>Animals do not use Replimat Animal Feeder
You'll need to provide more details before I can help you with your problem:
* What operating system, version and architecture (32 or 64-bit) are you running?
* What RimWorld game version are you running?
* What version of the Replimat mod are you running?
* Did you download this mod from Steam or GitHub?
* Did you experience the issue with only Core and Replimat loaded?
* Which specific animals are not using the Animal Feeder? (Colony animals? Wild Animals? A particular species of animal?)
* Are you running any other mods that may conflict with Replimat?

>我能用中文嗎?
No, please only report and discuss issues in English here on GitHub, as English is the universal language for discussing issues for open-source software.

**Comment by shiuanyue** [comment]
Colony animals  
I have used several mods.
Giddy-Up! mod 
Animal Food RestrictionIn Tab
Animal Food Restrictions
Hunt for Me and Kill For Me 
No way to troubleshoot immediately
Because usually when the problem arises, there are a lot of colonial animals

**Comment by sumghai** [comment]
Try removing all of the following mods and see what happens:
* Animal Food RestrictionIn Tab
* Animal Food Restrictions
* Hunt for Me and Kill For Me

**Comment by sumghai** [comment]
Closing as user did not report back with results from troubleshooting.
