### ISSUE TITLE
nutrition strangeness  

### ISSUE THREAD

**Issue by Dr-piss** [sumghai/Replimat#31]
im using android tiers and my colony subsists off of nutrient solution, something that has much higher nutrition than normal meat but when i put it into the system i get less feed stock than raw meats despite the fact that the solution has .15 nutrition and meats only have .5

**Comment by sumghai** [comment]
The Replimat Hopper's food-to-feedstock conversion is proportional to the mass of the food, not its nutritional value. 

This is intentional, as the Replimat mod obeys conservation of mass.
