### ISSUE TITLE
NRE at Replimat.ReplimatMod+StoreUtility_NoStorageBlockersIn.ReplimatHopperFilledEnough

### ISSUE THREAD

**Issue by SineSwiper** [sumghai/Replimat#34]
Seeing this NRE hit all the time:

```JobDriver threw exception in initAction for pawn Cashton driver=JobDriver_UnloadYourHauledInventory (toilIndex=1) driver.job=(UnloadYourHauledInventory (Job_2160860) A=Thing_ChunkSlagSteel2928417 B=(122, 0, 156))
System.NullReferenceException: Object reference not set to an instance of an object
  at Replimat.ReplimatMod+StoreUtility_NoStorageBlockersIn.ReplimatHopperFilledEnough (System.Boolean& __result, Verse.IntVec3 c, Verse.Map map, Verse.Thing thing) [0x00018] in <08f22a49ca55465693b94ab5f56a6f32>:0 
  at (wrapper dynamic-method) RimWorld.StoreUtility.DMD<DMD<NoStorageBlockersIn_Patch2>?1493542016::NoStorageBlockersIn_Patch2>(Verse.IntVec3,Verse.Map,Verse.Thing)
  at (wrapper dynamic-method) RimWorld.StoreUtility.DMD<DMD<IsGoodStoreCell_Patch1>?-1412940416::IsGoodStoreCell_Patch1>(Verse.IntVec3,Verse.Map,Verse.Thing,Verse.Pawn,RimWorld.Faction)
  at RimWorld.StoreUtility.TryFindStoreCellNearColonyDesperate (Verse.Thing item, Verse.Pawn carrier, Verse.IntVec3& storeCell) [0x000f2] in <93cc868ca2854db6a3f7a471e12e0cc2>:0 
  at PickUpAndHaul.JobDriver_UnloadYourHauledInventory+<>c__DisplayClass4_0.<MakeNewToils>b__0 () [0x00046] in <ac2642f61fbf46c5810ed34fcf95bf58>:0 
  at Verse.AI.JobDriver.TryActuallyStartNextToil () [0x001df] in <93cc868ca2854db6a3f7a471e12e0cc2>:0 
Verse.Log:Warning(String, Boolean)
Verse.AI.JobUtility:DMD<DMD<TryStartErrorRecoverJob_Patch1>?226248832::TryStartErrorRecoverJob_Patch1>(Pawn, String, Exception, JobDriver)
Verse.AI.JobDriver:TryActuallyStartNextToil()
Verse.AI.JobDriver:ReadyForNextToil()
Verse.AI.JobDriver:DMD<DMD<DriverTick_Patch1>?-1208635520::DriverTick_Patch1>(JobDriver)
Verse.AI.Pawn_JobTracker:JobTrackerTick()
Verse.Pawn:DMD<DMD<Tick_Patch1>?296539136::Tick_Patch1>(Pawn)
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:DMD<DMD<Update_Patch1>?1317555328::Update_Patch1>(Root_Play)
```

**Comment by sumghai** [comment]
Please provide additional troubleshooting information:

- What Operating System and version are you running?
- What RimWorld game version (including 32/64-bit) are you running?
- What Mods are you running?
- Have you narrowed down the specific mods you suspect to be conflicting with Replimat?
- Does your problem also occur if you only run a test savegame with only Core and Replimat?

**Comment by SineSwiper** [comment]
* Windows 10, 64-bit
* RimWorld, unstable build
* All of them
* Haven't done any bisecting, but I suspect it's either `Pick Up and Haul` or `Common Sense`.
* Given the stack trace, probably not, but I haven't tried it out yet.

Sorry, I was thinking the method just needed some NRE bulletproofing.  But, since I've got the example re-occurring error already, let me just write up a PR.

**Comment by sumghai** [comment]
> * All of them
> * Haven't done any bisecting, but I suspect it's either Pick Up and Haul or Common Sense.

Please perform a binary search and verify which mod is causing the incompatibility issue.

Also, as per the description on Steam Workshop and the mod order configuration included in Replimat's About file, have you tried making sure Common Sense is loaded after Replimat?

**Comment by SineSwiper** [comment]
Yes, Common Sense is loaded afterwards.  I can't extract Pick Up and Haul from my save game, because it breaks too many things.

The current fork doesn't seem to be up-to-date on GitHub.  Had to dodge around a few access modifiers on `IncidentWorker_*` classes that should be marked as `protected override`, among other build problems.

But, I was able to get a DLL working and fix the error with the following one-line fix:

```diff --git a/Source/HarmonyPatches.cs b/Source/HarmonyPatches.cs
index 827dd99..935b3cc 100644
--- a/Source/HarmonyPatches.cs
+++ b/Source/HarmonyPatches.cs
@@ -329,7 +330,7 @@ public static void ReplimatHopperFilledEnough(ref bool __result, IntVec3 c, Map
                 if (__result)
                 {

-                    if (c.GetSlotGroup(map).parent.GetType().ToString() == "Replimat.Building_ReplimatHopper")
+                    if (c.GetSlotGroup(map)?.parent?.GetType().ToString() == "Replimat.Building_ReplimatHopper")
                     {
                         // Apply the minimum Hopper refilling threshold only to Replimat Hoppers
                         __result &= !map.thingGrid.ThingsListAt(c).Any(t => t.def.EverStorable(false) && t.stackCount >= thing.def.stackLimit * Settings.HopperRefillThresholdPercent);
```

Just needed some NRE bulletproofing.  Can you throw this into a commit?

**Comment by sumghai** [comment]
> Yes, Common Sense is loaded afterwards. I can't extract Pick Up and Haul from my save game, because it breaks too many things.

While the point is now moot, the usual advice for troubleshooting is to start a new, temporary savegame _without_ Pick Up and Haul (or any mods other than Core and Replimat). Once you verify that Replimat isn't conflicting with the vanilla base game, then you can add your other mods back in slowly until you narrow down the culprit.

> The current fork doesn't seem to be up-to-date on GitHub. Had to dodge around a few access modifiers on `IncidentWorker_*` classes that should be marked as `protected override`, among other build problems.

I'm not sure what you mean by "doesn't seem to be up-to-date", since I have the source code right here on my machine and it compiles just fine. Perhaps the discrepancy is because @Dubwise56 and I are compiling from a publicized version of RimWorld's `Assembly-CSharp.dll`.

> But, I was able to get a DLL working and fix the error with the following one-line fix:

This looks easy enough on my end. I'll push a commit later today.

**Comment by sumghai** [comment]
@SineSwiper - I've just pushed a commit with your fix. Please try the following development build:

https://github.com/sumghai/Replimat/archive/6ac7a948bcfdac20b3da60c8e13efeaabb367a58.zip

**Comment by SineSwiper** [comment]
> While the point is now moot, the usual advice for troubleshooting is to start a new, temporary savegame without Pick Up and Haul (or any mods other than Core and Replimat). Once you verify that Replimat isn't conflicting with the vanilla base game, then you can add your other mods back in slowly until you narrow down the culprit.

Yeah, I know, but I took a look at the method and saw it was just a few lines.  Figured bulletproofing was way less effort, and I wasn't sure if I could duplicate it on a new game.  Sorry, should have made my intentions clearer.

> Perhaps the discrepancy is because @Dubwise56 and I are compiling from a publicized version of RimWorld's Assembly-CSharp.dll.

So, all of the methods are made public on that version?

> I've just pushed a commit with your fix. Please try the following development build:

Yep, that seems to work fine.

**Comment by sumghai** [comment]
> Perhaps the discrepancy is because @Dubwise56 and I are compiling from a publicized version of RimWorld's Assembly-CSharp.dll.
>> So, all of the methods are made public on that version?

Correct.

>I've just pushed a commit with your fix. Please try the following development build:
>> Yep, that seems to work fine.

Excellent. I'll mark this as resolved.

Please note that it'll be some time before I publish a release, as there are some other minor improvements in the pipeline.
