### ISSUE TITLE
Bulk creating packaged survival meals consumes incorrect amount of feedstock

### ISSUE THREAD

**Issue by CGamesPlay** [sumghai/Replimat#36]
When I click on "bulk create packaged survival meals", and created 1 meal, I was surprised to find that it consumed 5 of my total 7 L of feedstock. I tried a second time, and it consumed 1 of my remaining 2 L. When I examine [the code](https://github.com/sumghai/Replimat/blob/master/Source/Building_ReplimatTerminal.cs#L180) it seems as though `volumeOfFeedstockRequired` is the amount subtracted from my feedstock amount. `volumeOfFeedstockRequired` also appears to be the volume of feedstock required to create the maximum possible amount of meals.

**Comment by CGamesPlay** [comment]
Hey, thanks for addressing this quickly! Unfortunately I don't know how to do this--I install everything through the steam workshop. The referenced commit certainly looks like it fixes the issue, though.

**Comment by sumghai** [comment]
> Unfortunately I don't know how to do this--I install everything through the steam workshop.

Well, that's gonna be a doozy.

Try this:
1) In your operating system's file explorer/manager, navigate to the following directory:
`<Steam folder>\steamapps\workshop\content\294100\1715402900` - this should be the local Steam workshop folder for the Replimat mod
2) Open the `README.md` in a text editor (e.g. Notepad, Notepad++) and confirm that it is the readme file for the Replimat mod
3) Delete everything inside the `294100\1715402900` folder
4) Replace it with the contents from the development build ZIP file

**Comment by CGamesPlay** [comment]
Hey, haven't been able to get to Rimworld this weekend. If you need me to test, I will next time I start up the game. If you want to ship a version I can test through the steam workshop as well 😉

**Comment by sumghai** [comment]
@CGamesPlay - I don't push non-release dev builds to the Steam Workshop, so I suggest that you manually install the dev build using the instructions above. It really isn't that difficult to do.

**Comment by CGamesPlay** [comment]
No worries. I'll give it a shot next time I fire up Rimworld :)

~ry

**Comment by sumghai** [comment]
No further updates/feedback from OP, so I'm going to assume the fix works.

Closing.

**Comment by CGamesPlay** [comment]
Sorry, haven't gotten back to Rimworld :-/ Thanks for fixing this!
