### ISSUE TITLE
Feature request: WallStuff mod awareness / adaption or "industrial" replicator variant for materials.

### ISSUE THREAD

**Issue by amcgregor** [sumghai/Replimat#41]
Howdy!

Loving this mod.  It finally resolved the continuous cycle of my herd of animals failing to feed themselves and requiring medically assisted feeding, over and over and over again.  ("An animal needs rescue!" — got really tired of just ignoring that constant blinking warning.)  It also has finally provided a useful drain for my growing stockpiles of Human Meat: I'm up to 17,000L of replicator material just from that and the occasional insect, plus milk surplus.  (The optimized production pipelines I have for reprocessing dire raids: organs, excess organs → meat, implants, hollow shells of people → meat, cleaning of all tainted clothing, then disassembly of anything < masterwork quality… it's the stuff of horror.)

![processing](https://user-images.githubusercontent.com/76750/87673465-9af8ff80-c742-11ea-8865-064649158b00.png)

However!  There is another mod I use which provides a slightly different mechanism of action.  Instead of virtual containers pawns can retrieve items from, which are replicated on demand from stocks, [WallStuff](https://github.com/JohnCannon87/RimworldWallStuff) offers an in-wall mounted replicator panel which emits X items every Y period (e.g. every 24h), from a limited and explicitly configured set of possible materials. (Making it unlimited and rather cheesy, just explicit.)  It has a power cost, but that is it.  This does seem completely lacking balance—infinite Archotech items, please!—where your Replimat provides balance by requiring materials be broken down then that "proto-matter" consumed by mass of produced item.  Additional balance could be had by using the "tech level" of the item as a multiplier.  Neolithic 0.5×, Archotech 100×, for example, or by requiring an existing item be broken down before the "pattern" can be learned for replication.  Want more Archotech Arms?  Destroy the only one you have, first…

So far, I have enforced my own kind of balance in the selection of materials (base materials only, plus Poly), and adjusting the rate of delivery (fewer items per batch the higher-tech it is) and frequency (stone and steel are easy, poly is hard), but having no material cost still feels wrong. These in-wall "industrial" replicators could absolutely benefit from the same mass conversion and resource requirements as the food replimats.  Alternative to patching WallStuff, if present, would be to offer an explicit "industrial replimat" yourself, which also generates on a schedule, rather than on-demand.  In-wall is convenient for my storage area:

![materials](https://user-images.githubusercontent.com/76750/87673758-06db6800-c743-11ea-9791-d2230f27c3c4.png)

This is set up with the deep core miners to produce various ores up to a certain level, then any remaining "fill" is provided by the industrial replicators as they trickle additional resources into those containers directly. They "drop" the replicated item on the floor in front of themselves.  You can see one handy worker bot happily making more slate stone blocks to actively make up for a deficit.  I use a lot of slate.  😉

**Comment by sumghai** [comment]
I actually have plans for industrial replicators as well, but that will be another standalone mod with a different implementation.

Replimat will only focus on food - and maybe beverages in the future, if I can find the time to understand how to patch the related jobdrivers and toils).

**Comment by amcgregor** [comment]
I hope it will consume the same resource pool as the food replicators; protons, neutrons, and electrons are pretty universal.

**Comment by amcgregor** [comment]
Ah, additional idea, and one that… slightly counters the idea of having many mods to do one thing: medical replicators, replicating (on-demand) various qualities of medicine, exactly the same as the food replicators in usage and purpose.  And a fourth: production replicators, with scheduled jobs, permitting use of standard job limits, queueing, prioritization, and task assignment.  These, to me, all deserve to be a single mod covering the entire aspect of replication technology, unified by the dedicated "proto-matter" resource they should share.

**Comment by sumghai** [comment]
@amcgregor, while I appreciate your enthusiasm, the Replimat mod's focus is on food only. Again, I am considering an Industrial Replicator system, but it will be a separate mod unrelated to Replimat.

Please keep your posts in the issue tracker on-topic, and do not use this as a generic chatroom.

**Comment by amcgregor** [comment]
There we go, "trimmed the fat" for you.  Good day, sir.
