### ISSUE TITLE
Dubs Bad Hygiene integration - Biomass Recovery Unit

### ISSUE THREAD

**Issue by sumghai** [sumghai/Replimat#44]
Essentially converts a fixed fraction of sewage into nutrient feedstock.

Will need to discuss this with Dubs.

**Comment by sumghai** [comment]
[Raw sewage has a density of 721 kg/m³](https://www.aqua-calc.com/page/density-table/substance/sewage-coma-and-blank-sludge), or 0.72 kg/L.

For comparison, the density of Replimat's own nutrient feedstock is 1.07 kg/L (equivalent to Abbott's Ensure Nutritional Shake).

For game balance purposes, the conversion rate of sewage to usable feedstock would be a fixed value somewhere between 15~30%.

**Comment by sumghai** [comment]
Dubs notes that sewage is mostly water, so we'll go for 15% recovery.

**Comment by sumghai** [comment]
The sewage system in DBH works on a producer/consumer model like the vanilla power comp, and as it doesn't track the density and flow rate of sewage in the system, a Biomass Recovery Unit that simply takes 15% of whatever sewage goes through it will eventually convert all sewage into solid biomass over several iterations, even though after the very first pass the remaining 85% is already just water.

Dubs proposes two solutions:

- "Destroy" the 85% as water evaporated during the biomass recovery process (Dubs noted that water as a resource is practically unlimited anyway, with little gains from recycling)

- Recycle the 85% as fresh water back into the plumbing network (This would be useful for closed-loop environments like SOS2 spacecraft)

**Comment by sumghai** [comment]
IRL, sewage is actually 0.1% solids and 99.9% water:

https://www.epa.gov/sites/default/files/2015-06/documents/epa-mou_wastewater_basics_101.pdf

For gameplay and balance purposes, we should reduce the solids/water ratio to 5/95 instead.

**Comment by Peekabooxi** [comment]
Hey there,
I'am sorry if this is a redundant question or in the wrong tab. I tried to search for it as good as I could and ended here. 

I tried loading replicate first and I tried the other way around
 I get this error when I use the two together: 

Could not resolve cross-reference to Verse.ThingDef named ReplimatSewageRecycler (wanter=excludedThingDefs)
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.DirectXmlCrossRefLoader:TryResolveDef<Verse.ThingDef> (string,Verse.FailMode,object)
Verse.DirectXmlCrossRefLoader/WantedRefForList`1<Verse.ThingDef>:TryResolve (Verse.FailMode)
Verse.DirectXmlCrossRefLoader/<>c__DisplayClass16_1:<ResolveAllWantedCrossReferences>b__0 (Verse.DirectXmlCrossRefLoader/WantedRef)
Verse.GenThreading/<>c__DisplayClass7_1`1<Verse.DirectXmlCrossRefLoader/WantedRef>:<ParallelForEach>b__0 (object)
System.Threading.QueueUserWorkItemCallback:WaitCallback_Context (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.QueueUserWorkItemCallback:System.Threading.IThreadPoolWorkItem.ExecuteWorkItem ()
System.Threading.ThreadPoolWorkQueue:Dispatch ()
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback ()

**Comment by sumghai** [comment]
@Peekabooxi - Please follow [the troubleshooting guide](https://gist.github.com/sumghai/71da62f9f4a3c8f377acd1fd9655e6de) and open a new bug report using the template provided.
