### ISSUE TITLE
Mod Incompatability (DocWorld)

### ISSUE THREAD

**Issue by Glassofagua** [sumghai/Replimat#46]
**Describe the bug:**  
Option to build structures from this mod not in architect tab.  also not accessible via command palette mod.
worth noting the structures exist in game, (can buy them from traders)
**Expected behavior:**  
Ability to produce them from somewhere in the architect tab options

**Steps to reproduce:**  

1.Co install replimat with docworld mod (+it's dependencies), my mod order has Docworld and dependencies
2.
3.

**Additional information:**
Abbreviated Debug log from the following mod list debug log is similar if replimat is above docworld in load order
1.harmony
2core
3royalty
4 d9 frame work
5 docworld
6 replimat

RimWorld 1.2.2900 rev837
Verse.Log:Message(String, Boolean)
RimWorld.VersionControl:LogVersionNumber()
Verse.Root:CheckGlobalInit()
Verse.Root:Start()
Verse.Root_Entry:Start()

Tried loading mod with the same packageId multiple times: walkingproblem.aaf. Ignoring the duplicates.
C\

[DocWorld] Patch operation Verse.PatchOperationFindMod(Replimat) failed
\
Could not resolve cross-reference: No Verse.DesignationCategoryDef named Replimat_Replimat found to give to Verse.ThingDef 

Could not resolve cross-reference: No Verse.DesignationCategoryDef named Replimat_Replimat found to give to Verse.ThingDef 

## System and Game Configuration
**Operating System:* Microsoft Windows 10 (64-bit) 
**Physical RAM:** 32 gb
**RimWorld base game version:**  latest update 1.2.2900
**RimWorld DLCs loaded:** royalty
**Replimat mod version: yes latest steam update

**Your mod list:** 
1.harmony v1.0.4.0
2core
3royalty
4 d9 frame work  v 1.3.1
5 docworld v1.2.2.23 (29/11/2020)
6 replimat Version 1.2.4

## Declaration

I hereby verify that:
- [x] I am running the latest version of the game, Replimat and its dependencies
- [x] I am NOT running any mods with known incompatibilities with Replimat (I did not see it on the incompatibilities list on steam but I will not exclude the possibility That I am an idiot).
- [x] I have narrowed down my modlist to the fewest mods needed to cause this issue
- [x] I have confirmed that the issue does not happen if Replimat is disabled
- [x] I have searched the issue tracker and confirmed no-one else has reported my issue before (re: i could just be some idiot)
- [x] I understand that my issue will be closed and ignored if I do not fill this form properly

**Comment by sumghai** [comment]
I just had a chat with @DrZhivago1 - the issue will be fixed in the next release of DocWorld. 

Closing this as a third-party mod problem.
