### ISSUE TITLE
Terminals and Feeders not spawning food.

### ISSUE THREAD

**Issue by MrSonicOSG** [sumghai/Replimat#55]
**Describe the bug:**  
<Neither the feeders nor terminals would dispense meals aside from the batch survival meals, but it would play the animation.>

**Expected behavior:**  
<I was hoping for there to be food.>

**Steps to reproduce:**  
1. I honestly don't know, the bug started as soon I opened my save.
2.
3.

**Additional information:**
<Exception spawning loaded thing ReplimatAnimalFeeder2014729: System.NullReferenceException: Object reference not set to an instance of an object
  at Replimat.Building_ReplimatAnimalFeeder.SpawnSetup (Verse.Map map, System.Boolean respawningAfterLoad) [0x00045] in <270f91aee9d54996bdf76130280c0432>:0 
  at (wrapper dynamic-method) Verse.GenSpawn.Verse.GenSpawn.Spawn_Patch2(Verse.Thing,Verse.IntVec3,Verse.Map,Verse.Rot4,Verse.WipeMode,bool)
  at Verse.GenSpawn.SpawnBuildingAsPossible (Verse.Building building, Verse.Map map, System.Boolean respawningAfterLoad) [0x000f9] in <e13bd2f1929544099ed2b58e66ece833>:0 
  at (wrapper dynamic-method) Verse.Map.Verse.Map.FinalizeLoading_Patch0(Verse.Map)
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
(wrapper dynamic-method) Verse.Map:Verse.Map.FinalizeLoading_Patch0 (Verse.Map)
(wrapper dynamic-method) Verse.Game:Verse.Game.LoadGame_Patch3 (Verse.Game)
Verse.SavedGameLoaderNow:LoadGameFromSaveFileNow (string)
Verse.Root_Play/<>c:<Start>b__1_1 ()
Verse.LongEventHandler:RunEventFromAnotherThread (System.Action)
Verse.LongEventHandler/<>c:<UpdateCurrentAsynchronousEvent>b__27_0 ()
System.Threading.ThreadHelper:ThreadStart_Context (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object)
System.Threading.ThreadHelper:ThreadStart ()>

## System and Game Configuration
**Operating System:** <Windows 10 Pro>
**Physical RAM:** <32GB>
**RimWorld base game version:** <Latest.>
**RimWorld DLCs loaded:** <Royalty>
**Replimat mod version:** <Latest.>
**Replimat mod downloaded from:** <Steam.>
**Your mod list:** <If it just says latest it means I couldn't find the mod version number.
Harmony | 1.1.1.0
Share The Load | v2.3
HugsLib | v9
Replimat | v1.2.11
Humanoid Alien Races | v1.2
Proximity (Continued) | (latest)
Perfect Pathfinding | (Latest)
Android tiers | v3.0.0RC rev6
Archotech++ | (latest)
Androids | (Latest)
RocketMan - Performance Mod | (Latest)
More Archotech Garbage Reupload | (Latest)
Science Never Stops: Ambition of the Cosmic | V2.8
SNS AOTC: True Pinnacle of Creation | (Latest)
Science Never Stops: You're Going Too Far (SNS: AOTC Reskin) | V2.8>

## Declaration
I hereby verify that:
- [x] I am running the latest version of the game, Replimat and its dependencies
- [x] I am NOT running any mods with known incompatibilities with Replimat 
- [x] I have narrowed down my modlist to the fewest mods needed to cause this issue
- [x] I have confirmed that the issue does not happen if Replimat is disabled
- [x] I have searched the issue tracker and confirmed no-one else has reported my issue before
- [x] I understand that my issue will be closed and ignored if I do not fill this form properly

**Comment by MrSonicOSG** [comment]
Crap I forgot to mark that I have royalty.

**Comment by sumghai** [comment]
Without clear reproduction steps, there's practically no way for me to figure out how this issue has occured.

You also haven't narrowed down your modlist enough. Go back and verify that Replimat works on its own, then try different combinations of mods with Replimat until you've narrowed down the conflicting mods.

**Comment by MrSonicOSG** [comment]
1) like I said, the issue just started as soon as I loaded into my existing save, it spat the listed error at me as soon as I loaded in.

2) I HAVE narrowed it down, that modlist is close to 100 mods normally.

3) I do not have the time to bug test your own mod as I work 50+ hour weeks. For now I think I'll just revert to the last version.

**Comment by sumghai** [comment]
> like I said, the issue just started as soon as I loaded into my existing save, it spat the listed error at me as soon as I loaded in.

Have you tried deconstructing and reconstructing all your Animal Feeders?

> I HAVE narrowed it down, that modlist is close to 100 mods normally.

Usually, any bugs involve only one or two mods having incompatibility issues with Replimat, not 15 mods simultaneously.

> I do not have the time to bug test your own mod as I work 50+ hour weeks. For now I think I'll just revert to the last version.

Given my IRL workload is similar to yours, I have limited time and resources available to RimWorld modding, so I would appreciate players reporting bugs to make the effort to narrow down the bare minimum number of mods and clear steps to reproduce this issue in a quick and timely manner. 

If you are not inclined to do so, then I guess we're at an impasse.
