### ISSUE TITLE
xml errors

### ISSUE THREAD

**Issue by ohaha233** [sumghai/Replimat#56]
**Describe the bug:**  
when the game starts, red errors show up.

**Expected behavior:**  
no error shows up.

**Steps to reproduce:**  

1. start the game
2.
3.

**Additional information:**
![1](https://user-images.githubusercontent.com/42904744/141793737-c8bf4b51-51c8-431b-80a2-156d00da32b7.PNG)

![2](https://user-images.githubusercontent.com/42904744/141794191-8aeeac7e-0582-46c0-82a1-04da1180e58a.PNG)

Could not find type named Replimat.CompProperties_ReplimatRestrictions from node <li Class="Replimat.CompProperties_ReplimatRestrictions"><disallowedMeals><li>VCE_RuinedSimpleGrill</li><li>VCE_RuinedFineGrill</li><li>VCE_RuinedLavishGrill</li><li>VCE_RuinedGourmetGrill</li></disallowedMeals><disallowedIngredients><li>VCE_CannedMeat</li><li>VCE_CannedProduce</li><li>VCE_CannedFruit</li><li>VCE_CannedAP</li><li>VCE_CannedFish</li><li>VCE_DigestibleResurrectorNanites</li></disallowedIngredients></li>

XML error: <disallowedMeals><li>VCE_RuinedSimpleGrill</li><li>VCE_RuinedFineGrill</li><li>VCE_RuinedLavishGrill</li><li>VCE_RuinedGourmetGrill</li></disallowedMeals> doesn't correspond to any field in type CompProperties. Context: <li Class="Replimat.CompProperties_ReplimatRestrictions"><disallowedMeals><li>VCE_RuinedSimpleGrill</li><li>VCE_RuinedFineGrill</li><li>VCE_RuinedLavishGrill</li><li>VCE_RuinedGourmetGrill</li></disallowedMeals><disallowedIngredients><li>VCE_CannedMeat</li><li>VCE_CannedProduce</li><li>VCE_CannedFruit</li><li>VCE_CannedAP</li><li>VCE_CannedFish</li><li>VCE_DigestibleResurrectorNanites</li></disallowedIngredients></li>

XML error: <disallowedIngredients><li>VCE_CannedMeat</li><li>VCE_CannedProduce</li><li>VCE_CannedFruit</li><li>VCE_CannedAP</li><li>VCE_CannedFish</li><li>VCE_DigestibleResurrectorNanites</li></disallowedIngredients> doesn't correspond to any field in type CompProperties. Context: <li Class="Replimat.CompProperties_ReplimatRestrictions"><disallowedMeals><li>VCE_RuinedSimpleGrill</li><li>VCE_RuinedFineGrill</li><li>VCE_RuinedLavishGrill</li><li>VCE_RuinedGourmetGrill</li></disallowedMeals><disallowedIngredients><li>VCE_CannedMeat</li><li>VCE_CannedProduce</li><li>VCE_CannedFruit</li><li>VCE_CannedAP</li><li>VCE_CannedFish</li><li>VCE_DigestibleResurrectorNanites</li></disallowedIngredients></li>

## System and Game Configuration
**Operating System: Microsoft Windows 10 (64-bit)
**Physical RAM: 16.0 GB
**RimWorld base game version: 1.2.3005
**RimWorld DLCs loaded: Royalty 
**Replimat mod version: 1.2.11
**Replimat mod downloaded from: Steam 
**Your mod list:

<?xml version="1.0" encoding="utf-8"?>
<ModsConfigData>
  <version>1.2.3005 rev1190</version>
  <activeMods>
    <li>brrainz.harmony</li>
    <li>ludeon.rimworld</li>
    <li>ludeon.rimworld.royalty</li>
    <li>oskarpotocki.vanillafactionsexpanded.core</li>
    <li>vanillaexpanded.vcooke</li>
    <li>sumghai.replimat</li>
  </activeMods>
  <knownExpansions>
    <li>ludeon.rimworld.royalty</li>
  </knownExpansions>
</ModsConfigData>

## Declaration

I hereby verify that:
- [ ] I am running the latest version of the game, Replimat and its dependencies
- [x] I am NOT running any mods with known incompatibilities with Replimat 
- [x] I have narrowed down my modlist to the fewest mods needed to cause this issue
- [x] I have confirmed that the issue does not happen if Replimat is disabled
- [x] I have searched the issue tracker and confirmed no-one else has reported my issue before
- [x] I understand that my issue will be closed and ignored if I do not fill this form properly

**Comment by sumghai** [comment]
You are not running the latest version of the game (1.3), and you didn't narrow down your modlist to the bare minimum required to reproduce this bug.

Please follow the instructions exactly as provided.

**Comment by ohaha233** [comment]
some mods doesn't update to 1.3, so i stay in 1.2.

**Comment by sumghai** [comment]
As of July 2021, all Replimat-related updates are for RimWorld 1.3 only. 

I am not going to make any RW 1.3 features backwards compatible for 1.2, so the most I plan to do is to prevent any 1.3-specific XML from being referenced in 1.2.
