### ISSUE TITLE
Translation into German

### ISSUE THREAD

**Issue by RandyRagequit** [sumghai/Replimat#62]
**Describe your idea:**

The idea is pretty simple. Just an additional translation into German language. Did some of the work already, tho I am not sure if this is everything needed for full translation. 

**Why do you think your idea would be a good fit for Replimat?:**

I think of it as a good idea since I came across several Rimworld players using this mod natively speaking German and I think it might attract even more players native to German language if a translation is availabe since there are many people not quite as trained in English language.

## Declaration

I hereby verify that:
- [x] I have searched the issue tracker and confirmed no-one else has already suggested my idea before
- [x] I understand that my idea will be closed and ignored if I do not fill this form properly, or if the mod author decides that my idea doesn't fit the scope of the mod
[GERtranslation.zip](https://github.com/sumghai/Replimat/files/8128982/GERtranslation.zip)

**Comment by RandyRagequit** [comment]
I hope I did this right, since I have no  training it Github whatsoever. Please hit me up if any more text is available and needed to complete the full Replimat translation

**Comment by sumghai** [comment]
Hi @RandyRagequit!

Although what you did (strictly speaking) isn't what GitHub would consider a pull request, I'm more than happy to take what you've uploaded here and include them in the upcoming update.

That being said, I've noticed you've only provided translations for the Keyed strings - a full German translation of Replimat would also require string replacements for DefInjected text. Have a look at how it was done for the Russian translation:

https://github.com/sumghai/Replimat/tree/master/Common/Languages/Russian/DefInjected

**Comment by RandyRagequit** [comment]
Hi there, thank you very much and at the same time excuse me, I did my best in finding out the right thing but messed up haha. Thanks for the heads up! I'll definitely check it out and hit you up on Rimworld's discord!

**Comment by RandyRagequit** [comment]
[GERtranslation.zip](https://github.com/sumghai/Replimat/files/8137467/GERtranslation.zip)
 
 Hey folks, so this is what I worked out today already. I doulbe and triple-checked that I didn't miss a thing, so there should everything be available.  Looking forward on how you like it.
 
 Greetings
 
 PS: I added the file I did earlier on this post, just in case!
