### ISSUE TITLE
Error while trying to feed a baby through a Replimat Terminal

### ISSUE THREAD

**Issue by MaxX-O1** [sumghai/Replimat#70]
**Describe the bug:**  
It seems that Replimat throw an error when trying to feed a baby through the terminal, the pawn gets to it but just stands there and can't replicate baby food. I've removed every mods and tested with Replimat only and it still happens.

**Expected behavior:**  
I expected that the pawn carries out to replicate some baby food without any issue and feed the baby.

**Steps to reproduce:**  

1. Have a newborn child and no mother/lactating pawn
2. Let the child go hungry
3. Either a pawn try to get some food through a Replimat terminal, or make them via "Prioritize feeding 'baby'"
4. The pawn will stand near the terminal without being able to retrieve any food

**Additional information:**

![Replimat](https://user-images.githubusercontent.com/31326853/198857535-b4239b75-02ee-49c1-b05b-3a306ad9f78d.png)

JobDriver threw exception in toil TakeToInventory's initAction for pawn Hiroto driver=JobDriver_BottleFeedBaby (toilIndex=3) driver.job=(BottleFeedBaby (Job_6350) A=Thing_Human562 B=Thing_ReplimatTerminal23040)
System.NullReferenceException: Object reference not set to an instance of an object
  at RimWorld.FoodUtility.WillIngestStackCountOf (Verse.Pawn ingester, Verse.ThingDef def, System.Single singleFoodNutrition) [0x00000] in <f4c3e52a3fec4807a874d50b5e1c361f>:0 
  at RimWorld.JobDriver_BottleFeedBaby.<MakeNewToils>b__8_2 (Verse.Thing babyFood) [0x00018] in <f4c3e52a3fec4807a874d50b5e1c361f>:0 
  at Verse.AI.Toils_Haul+<>c__DisplayClass11_0.<TakeToInventory>b__0 () [0x00056] in <f4c3e52a3fec4807a874d50b5e1c361f>:0 
  at Verse.AI.JobDriver.TryActuallyStartNextToil () [0x001b0] in <f4c3e52a3fec4807a874d50b5e1c361f>:0 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.AI.JobUtility:TryStartErrorRecoverJob (Verse.Pawn,string,System.Exception,Verse.AI.JobDriver)
Verse.AI.JobDriver:TryActuallyStartNextToil ()
Verse.AI.JobDriver:ReadyForNextToil ()
Verse.AI.JobDriver:Notify_PatherArrived ()
Verse.AI.Pawn_PathFollower:PatherArrived ()
Verse.AI.Pawn_PathFollower:TryEnterNextPathCell ()
Verse.AI.Pawn_PathFollower:PatherTick ()
Verse.Pawn:Tick ()
Verse.TickList:Tick ()
Verse.TickManager:DoSingleTick ()
Verse.TickManager:TickManagerUpdate ()
Verse.Game:UpdatePlay ()
Verse.Root_Play:Update ()

## System and Game Configuration
**Operating System:** Microsoft Windows 11 (64-bit)
**Physical RAM:** 16.0 GB
**RimWorld base game version:** 1.4.3531
**RimWorld DLCs loaded:** Royalty, Ideology, Biotech
**Replimat mod version:** 1.4.1
**Replimat mod downloaded from:** Steam
**Your mod list:** Harmony 2.2.2, Replimat 1.4.1

## Declaration

I hereby verify that:
- [x] I am running the latest version of the game, Replimat and its dependencies
- [x] I am NOT running any mods with known incompatibilities with Replimat 
- [x] I have narrowed down my modlist to the fewest mods needed to cause this issue
- [x] I have confirmed that the issue does not happen if Replimat is disabled
- [x] I have searched the issue tracker and confirmed no-one else has reported my issue before
- [x] I understand that my issue will be closed and ignored if I do not fill this form properly

**Comment by sumghai** [comment]
Bug confirmed - thank you for the excellent bug report.

Looks like `JobDriver_BottleFeedBaby()` isn't patched to account for Replimat as a dispenser, so pawns are mistaking Terminals for Baby Food, and are literally trying (and failing) to lift a Terminal off the ground and feed it to the baby.

I'll see what I can do over the next few days.

**Comment by sumghai** [comment]
Pawns bottle-feeding babies from the Replimat Terminal will now replicate baby food and put it into their inventory, before proceeding to pick up the baby for feeding as usual.
