### ISSUE TITLE
Error on selecting animals on caravan

### ISSUE THREAD

**Issue by Quarta-feira** [sumghai/Replimat#76]
**Describe the bug:**  

When forming a caravan, an error is shown when I select an animal. (tested Labrador Retriever, Husky and donkey)''

**Expected behavior:**  

To not show an error

**Steps to reproduce:**  

1. Start new game in dev mode
2. Unforbid all items and make a home zone over food items
3. Make a Caravan with pawns and animals

**Additional information:**

mention of replimat:
Exception filling window for RimWorld.Dialog_FormCaravan: System.InvalidOperationException: Nullable object must have a value.
  at System.Nullable`1[T].get_Value () [0x00008] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at Replimat.Harmony_FoodUtility_ThoughtsFromIngesting.Postfix (System.Collections.Generic.List`1[RimWorld.FoodUtility+ThoughtFromIngesting]& __result, Verse.Pawn ingester, Verse.Thing foodSource, Verse.ThingDef foodDef) [0x00060] in <4ef0e42b6415427ca254993a27d562f7>:0 

Full log on the git link: https://gist.github.com/0b29ea98e8affae21eb3a1dd47bf62a6

## System and Game Configuration
**Operating System:**  Windows 11 Pro 22H2
**Physical RAM:**  16GB
**RimWorld base game version:**  1.4.3566 rev686
**RimWorld DLCs loaded:** 
**Replimat mod version:**  1.4.4
**Replimat mod downloaded from:**  Steam
**Your mod list:**  harmony 1.5.0.0, core 1.4.3566, hugslib 10.0.1 (+owlchemist fix search fork)

## Declaration

I hereby verify that:
- [x] I am running the latest version of the game, Replimat and its dependencies
- [x] I am NOT running any mods with known incompatibilities with Replimat 
- [x] I have narrowed down my modlist to the fewest mods needed to cause this issue
- [x] I have confirmed that the issue does not happen if Replimat is disabled
- [x] I have searched the issue tracker and confirmed no-one else has reported my issue before
- [x] I understand that my issue will be closed and ignored if I do not fill this form properly

**Comment by sumghai** [comment]
Bug confirmed and fixed!
