### ISSUE TITLE
Increased difficulty setting

### ISSUE THREAD

**Issue by databobek** [sumghai/Replimat#77]
**Describe your idea:**
 Consider an optional setting in the options "Hardcore mode" for example. It should increase the costs (research, build and power usage) of the Replimat system. Consider a slider "food cost" that would apply a multiplier to the food mass needed to create a meal (increase/decrease).

**Why do you think your idea would be a good fit for Replimat?:**
I think both Replimat and MedPod are some of the bests mods out there, very vanilla-fitting and well-done, however they make the game quite a breeze to go through, especially when combined with other mods.

**What alternatives/workarounds have you tried?**
I have personally made an Ambition of the Cosmic Patch to move the Replimat (and MedPod) behind the stellar technology, requiring the more exoctic parts and increased the power usage of the computer/terminals 10-fold.

## Declaration

I hereby verify that:
- [x] I have searched the issue tracker and confirmed no-one else has already suggested my idea before
- [x] I understand that my idea will be closed and ignored if I do not fill this form properly, or if the mod author decides that my idea doesn't fit the scope of the mod

**Comment by sumghai** [comment]
I have no plans for additional difficulty settings.
