### ISSUE TITLE
Market value balance

### ISSUE THREAD

**Issue by solidDoWant** [sumghai/Replimat#86]
**Describe your idea:**

The market value of Replimat buildings is significantly higher than the cost of the components that make them. This means that as soon as any Replimat buildings are built, the game difficulty goes up significantly when using any storyteller that scales based on colony wealth (most of them). I understand if this was intended to help balance the mod a bit, but it'd be nice if there was a mod option to adjust the market value in game, instead of modifying the Buildings def.

![image](https://github.com/sumghai/Replimat/assets/16456946/eaf25a73-e820-43c1-980e-7fb36e3cc393)
_Spikes are when I built Replimat buildings_

**Why do you think your idea would be a good fit for Replimat?:**

It'd allow players to more easily balance the mod to fit their playstyle

**What alternatives/workarounds have you tried?**

Modifying the `Buildings_Replimat.xml` def file

## Declaration

I hereby verify that:
- [x] I have searched the issue tracker and confirmed (to the best of my ability) that no-one else has already suggested my idea before
- [x] I understand that my idea will be closed and ignored if I do not fill this form properly, or if the mod author decides that my idea doesn't fit the scope of the mod

**Comment by sumghai** [comment]
Sorry, I have no plans to add additional mod settings to Replimat.

With regards to the market value, the value of a item or building is not merely the sum of cost of the components, but should also consider the precision and skilled labor required to design/assemble the equipment, (hypothetical) intellectual property licensing fees, as well as perceived value.

As endgame facilities, both Replimat and MedPod are already overpowered enough to warrant attracting very high level raids through its high market value.

**Comment by solidDoWant** [comment]
Alright. For what it's worth, a setting like this could be used to _increase_ the value, not just decrease it. If the argument is that the value should be high to trigger raids more often/make raids more difficult, then some users might want to raise it either higher.

If anybody comes across this thread and wants to change the market values manually, here's how:
1. Find the `Buildings_Replimat.xml` file. If the mods was installed via the Steam workshop, then it's probably under `C:\Program Files (x86)\Steam\steamapps\workshop\content\294100\1715402900\Common\Defs\ThingDefs_Buildings\Buildings_Replimat.xml`. 
2. Open the file with a text file editor (such as Notepad).
3. Search for the `<MarketValue>` tags ([example here](https://github.com/sumghai/Replimat/blob/master/Common/Defs/ThingDefs_Buildings/Buildings_Replimat.xml#L53)). There is one per building, so currently 6. Change the enclosed value for each tag to whatever market value you'd like. Personally, I found that 1% of the original value is about inline with all the other mods I'm using. The exact value depends on how you think the mod should be balanced.
4. Repeat the above, but for the `<MarketValueIgnoreHp>` tags.
5. Save the file, and reload the game.
6. (Optional) If you're using the [Vanilla Trading Expanded mod](https://steamcommunity.com/workshop/filedetails/?id=2785616901), then you will need to go into the settings for that mod and reset trade prices. Alternatively you modify the values for each building in your save file, under the `priceModifiers` tag.

Note that these steps will need to be performed every time the mod updates.

**Comment by sumghai** [comment]
I do not recommend directly editing mod files between mod updates.

If you wish to "rebalance" the market value for whatever reason, I recommend writing a patch mod using XPath Operations instead.
