### ISSUE TITLE
Smokeleaf incident cannot be disabled

### ISSUE THREAD

**Issue by volpol** [sumghai/Replimat#88]
**Describe the bug:**  
Smokeleaf malfunction happened despite being seemingly disabled in the mod settings.

**Expected behavior:**  
Smokeleaf malfunction does not happen.

**Steps to reproduce:**  

1. Start a colony
2. Build all necessary Replimat infrastructure
3. Wait.

**Additional information:**

The issue is caused by the GUI checkbox for the setting referencing the "EnableIncidentKibble" field (Settings.cs, line 44), same as the checkbox for the Kibble Incident, instead of the correct "EnableIncidentSmokeleaf".
## System and Game Configuration
**Operating System:** Linux 6.10.6 x86_64
**Physical RAM:** 32 GB
**RimWorld base game version:** 1.5.4104
**RimWorld DLCs loaded:** Royalty, Ideology, Biotech, Anomaly
**Replimat mod version:** 1.5.6
**Replimat mod downloaded from:** GitHub
**Your mod list:** Not relevant, this is Replimat internal issue.

## Declaration

I hereby verify that:
- [x] I am running the latest version of the game, Replimat and its dependencies
- [x] I am NOT running any mods with known incompatibilities with Replimat 
- [x] I have narrowed down my modlist to the fewest mods needed to cause this issue
- [x] I have confirmed that the issue does not happen if Replimat is disabled
- [x] I have searched the issue tracker and confirmed no-one else has reported my issue before
- [x] I understand that my issue will be closed and ignored if I do not fill this form properly

**Comment by sumghai** [comment]
Oooh, good catch! Should be an easy fix.

**Comment by sumghai** [comment]
...and fixed for the next update. Thanks again!
