### ISSUE TITLE
Colonist stuck at Replimat Terminal while trying to replicate baby food

### ISSUE THREAD

**Issue by meihaiyin1993** [sumghai/Replimat#89]
**Describe the bug:**  

When feeding a baby, the little person will stand still and continuously retrieve baby food from the device.

I have recorded a video and attached it.

https://github.com/user-attachments/assets/d44bcf92-2d7e-4d26-925f-032e81f23859

**Expected behavior:**  

Take baby food once and leave the device

**Steps to reproduce:**  

1.When a baby needs to be fed
2.
3.

**Additional information:**

![ebc2a92729ffedc71a0684597c369c4](https://github.com/user-attachments/assets/efdc60f0-14b8-42c2-b53f-0f0a4881fb84)

## System and Game Configuration
**Operating System:** 
**Physical RAM:** 
**RimWorld base game version:** 
**RimWorld DLCs loaded:** 
**Replimat mod version:** 
**Replimat mod downloaded from:** 
**Your mod list:** 

## Declaration

I hereby verify that:
- [ ] I am running the latest version of the game, Replimat and its dependencies
- [ ] I am NOT running any mods with known incompatibilities with Replimat 
- [ ] I have narrowed down my modlist to the fewest mods needed to cause this issue
- [ ] I have confirmed that the issue does not happen if Replimat is disabled
- [ ] I have searched the issue tracker and confirmed no-one else has reported my issue before
- [ ] I understand that my issue will be closed and ignored if I do not fill this form properly

**Comment by sumghai** [comment]
@meihaiyin1993, as you have not followed the proper bug reporting template and provided the required troubleshooting information, I am closing this issue as invalid.

You may reopen the issue in the future once you have the missing information.
